### ISSUE TITLE
Configure ACE Editor

### ISSUE THREAD

**Issue by kennyhei** [codebrowser/web-client#15]
Configure ACE Editor to suit project's needs
- Read-only
- Line numbering (show Gutter)
- Suitable font size (can be a setting in the future)
- Code Folding (mark begin and end)
- Key Binding (ACE)
- Line length 120 characters
- Highlight Active Line
- Do not show invisibles
- Do not show indentation guide
- Do not show persistent HScroll
- Do not animate scrolling
- Show print margin
- Do not use soft tab
- Highlight selected words
- Do not show token info

Create template view for ACE Editor

**Comment by kasper** [comment]
Should be ready to merge to master.

**Comment by kasper** [comment]
Merged to master.
